-- cursor que seleciona um cliente aleatório
--SELECT * FROM [TABELA DE CLIENTES]

DECLARE @CLIENTE_ALEATORIO VARCHAR(12)
DECLARE @VAL_INICIAL INT
DECLARE @VAL_FINAL INT
DECLARE @ALEATORIO INT
DECLARE @CONTADOR INT

SET @CONTADOR = 1 
SET @VAL_INICIAL = 1 -- cliente aleatorio começa com 1
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE CLIENTES] -- termina com o numero de clientes que exite na tabela
SET @ALEATORIO = dbo.[NumeroAleatorio](@VAL_INICIAL,@VAL_FINAL) -- variável q ecebe a func NumeroAleatorio

DECLARE CURSOR3 CURSOR FOR SELECT CPF FROM [TABELA DE CLIENTES]
OPEN CURSOR3
FETCH NEXT FROM CURSOR3 INTO @CLIENTE_ALEATORIO

WHILE @CONTADOR < @ALEATORIO -- percorre da posição 1 até a posição do num aleatorio
BEGIN
    FETCH NEXT FROM CURSOR3 INTO @CLIENTE_ALEATORIO
    SET @CONTADOR = @CONTADOR + 1
END

CLOSE CURSOR3
DEALLOCATE CURSOR3
SELECT @CLIENTE_ALEATORIO AS [CLIENTE ALEATÓRIO], @ALEATORIO AS [NUMERO ALEATÓRIO]
SELECT * FROM [TABELA DE CLIENTES]