-- escreva um programa em T-SQL que use um cursor para percorrer todas as linhas de uma tabela e imprima o nome dos funcionários e alguma outra coluna relacionada.
-- BASE SUCOS_FRUTAS
--SELECT * FROM [dbo].[TABELA_DE_VENDEDORES]

DECLARE @NOME_VENDEDOR VARCHAR(100)
		, @PERC_COMISSAO FLOAT

DECLARE FUNCIONARIO_CURSOR CURSOR FOR 
	SELECT NOME, PERCENTUAL_COMISSAO

FROM [TABELA_DE_VENDEDORES]
OPEN FUNCIONARIO_CURSOR

FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @NOME_VENDEDOR, @PERC_COMISSAO
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'NOME DO VENDEDOR: '+ @NOME_VENDEDOR + ' ' + ' PERCENTUAL DE COMISSÃO: ' + CONVERT(VARCHAR, @PERC_COMISSAO) 
    FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @NOME_VENDEDOR, @PERC_COMISSAO 
END

CLOSE FUNCIONARIO_CURSOR;
DEALLOCATE FUNCIONARIO_CURSOR;


