DECLARE @NUMERO_INICIAL_SEQUENCIA INT;
DECLARE @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
CREATE TABLE #TAB_NUM ([NUMERO] INT, [STATUS] VARCHAR(20));

-- A TABELA TEMPORÁRIA CRIADA COM @ É DECLARADA COMO UMA VARIÁVEL DENTRO DO SCRIPT E É VÁLIDA SÓ QUANDO EXECUTO O SCRIPT 1 VEZ
DECLARE @TABELA_DE_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(20));

SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 200;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA
BEGIN
	SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] 
	WHERE NUMERO = @NUMERO_INICIAL_SEQUENCIA
	
	IF @TESTE_NOTA_FISCAL = 1
		BEGIN
			INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
			VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É nota fiscal');

			INSERT INTO #TAB_NUM ([NUMERO], [STATUS]) 
			VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É nota fiscal')
		END;
	ELSE
		BEGIN
			INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
			VALUES (@NUMERO_INICIAL_SEQUENCIA, 'Não é nota fiscal');

			INSERT INTO #TAB_NUM ([NUMERO], [STATUS]) 
			VALUES (@NUMERO_INICIAL_SEQUENCIA, 'Não é nota fiscal');
		END;
	SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END;

SELECT * FROM @TABELA_DE_NUMEROS;
SELECT * FROM #TAB_NUM;