SELECT * FROM #X_MAN;
-- todas as conexões
CREATE TABLE ##AVENGERS (ID VARCHAR(10), NOME VARCHAR(30));
INSERT INTO ##AVENGERS VALUES ('1','Tony Stark');
INSERT INTO ##AVENGERS VALUES ('2','Steve Rogers');
SELECT * FROM ##AVENGERS;