/*Exercício
Impedir que o cliente compre mais do que é especificado no volume de compra no cadastro do cliente
*/

-- SAÍDA CPF MES, ANO E QTD TOTAL GASTO EM COMPRAS POR CPF
SELECT NF.CPF, 
	   CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO, -- CONVERTE A DATA MOSTRANDO APENAS MES E ANO COM A MASCARA 120 
	   SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM  NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) -- SOMANDO A QTD POR DATA QUE CADA CPF FEZ

SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;

-- SUBQUERY PARA VERIFICAR SE O CLIENTE NÃO EXCEDEU O LIMITE DE COMPRA
SELECT TC.CPF, TC.NOME, 
	   TC.VOLUME_DE_COMPRA, -- LIMITE DO CLIENTE
	   TOTAL_VENDA.MES_ANO, 
	   TOTAL_VENDA.QUANTIDADE_TOTAL -- O TOTAL VENDIDO

FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
	SELECT NF.CPF, 
		   CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO, 
		   SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
	FROM  NOTAS_FISCAIS NF
	INNER JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	GROUP BY NF.CPF, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TOTAL_VENDA -- ALIAS DA SUBQUERY

ON TOTAL_VENDA.CPF = TC.CPF

-- CLASSIFICAR QUAIS CPFS TIVERAM O VOLUME DE COMPRA DENTRO DO LIMITE E QUAIS TIVERAM O VOLUME DE COMPRA EXCEDIDO

SELECT TC.CPF, TC.NOME, 
	   TC.VOLUME_DE_COMPRA, 
	   TOTAL_VENDA.MES_ANO,
	   TOTAL_VENDA.QUANTIDADE_TOTAL,

	   (CASE WHEN TC.VOLUME_DE_COMPRA >= TOTAL_VENDA.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
	   ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO

FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF, 
	   CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO, 
	   SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM  NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TOTAL_VENDA -- ALIAS DA SUBQUERY

ON TOTAL_VENDA.CPF = TC.CPF

-- FILTRANDO POR MES E ANO

SELECT TC.CPF, TC.NOME, 
	   TC.VOLUME_DE_COMPRA, 
	   TOTAL_VENDA.MES_ANO,
	   TOTAL_VENDA.QUANTIDADE_TOTAL,
	   CONCAT(ROUND((TOTAL_VENDA.QUANTIDADE_TOTAL/ TC.VOLUME_DE_COMPRA -1)*100, 2), '%') AS DIFERENCA, --PERCENTUAL DA DIFERENÇA
	   (CASE WHEN TC.VOLUME_DE_COMPRA >= TOTAL_VENDA.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
	   ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO

FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF, 
	   CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO, 
	   SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM  NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TOTAL_VENDA -- ALIAS DA SUBQUERY

ON TOTAL_VENDA.CPF = TC.CPF
WHERE TOTAL_VENDA.MES_ANO = '2015-01'

-- FILTRO PARA OS CLIENTES QUE EXCEDERAM SEUS LIMITES

SELECT TC.CPF, TC.NOME, 
	   TC.VOLUME_DE_COMPRA, 
	   TOTAL_VENDA.MES_ANO,
	   TOTAL_VENDA.QUANTIDADE_TOTAL,
	   (CASE WHEN TC.VOLUME_DE_COMPRA >= TOTAL_VENDA.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
	   ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO

FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF, 
	   CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO, 
	   SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM  NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TOTAL_VENDA -- ALIAS DA SUBQUERY

ON TOTAL_VENDA.CPF = TC.CPF
WHERE TOTAL_VENDA.MES_ANO = '2015-01'
AND (TC.VOLUME_DE_COMPRA - TOTAL_VENDA.QUANTIDADE_TOTAL) < 0

