-- Classificando os campos
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA';

-- CLASSIFICA OS PRODUTOS DE ACORDO COM OS CRITÉRIOS CRIADOS COM O FILTRO WHEN, 
-- CRIADO UMA NOVA COLUNA CLASSIFICAÇÃO PARA ARMAZENAR ESSES VALORES
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICAÇÃO
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA'
ORDER BY CLASSIFICAÇÃO;


-- AGRUPANDO PELA CLASSIFICAÇÃO
SELECT
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA > = 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICAÇÃO, COUNT(*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA'
-- PARA AGRUPAR A CONSULTA REPETE A EXPRESSÃO DE CLASSIFICAÇÃO
GROUP BY (CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END);


/*
Para cada cliente temos seus limites de crédito mensais. Liste somente o nome dos clientes e os classifique por:

Acima ou igual a 150.000 - Clientes grandes
Entre 150.000 e 110.000 - Clientes médios
Menores que 110.000 Clientes pequenos
*/

SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTES GRANDES'
	  WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO <= 150000 THEN 'CLIENTES MÉDIOS'
	  ELSE 'CLIENTES PEQUENOS' END) AS CLASSIFICAÇÃO
FROM TABELA_DE_CLIENTES
ORDER BY CLASSIFICAÇÃO;
