-- BASE SUCOS_FRUTAS
--  Cláusula DISTINCT no comando
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS; -- TIRA A REPETIÇÃO DE LINHAS COM O MESMO DADO

-- DISTINCT COM FILTRO
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MACA';

-- combinações diferentes entre os campos embalagem e sabor
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;

-- Tendo em conta nossa tabela de produtos, execute uma consulta para obter o número de sabores existentes
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS; -- RESULTADO 12

-- **************** SELECT DISTINCT TOP ****************
-- TRAZ AS PRIMEIRAS LINHAS DE UMA TB

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM

-- TRAZ AS EMBALAGENS EXISTENTES
SELECT DISTINCT TOP 5
  EMBALAGEM
FROM TABELA_DE_PRODUTOS;

-- TRAZ AS EMBALAGENS Q TEM SUCO DE MAÇÃ
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MACA';

-- Tendo em vista os conteúdos trabalhados em aula, qual é o comando SQL para listar as 10 primeiras vendas do dia 01/10/2017?
SELECT TOP 10 * FROM NOTAS_FISCAIS
WHERE DATA_VENDA = '2017-10-01';

SELECT TOP 10 * FROM NOTAS_FISCAIS
WHERE DATA_VENDA = '2015-01-01'

-- ORDENANDO

-- POR DEFAULT ORDENA ASC
SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA;

-- ORDENA DECRESCENTE
SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC;

-- ORDENANDO A STRING (ORDEM ALFABETICA)
SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY NOME_DO_PRODUTO;

-- ORDENA TANTO EMBALAGEM QUANTO NOME_DO_PRODUTO EM ORDEM ASCENDENTE
SELECT EMBALAGEM, NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

-- ORDENA TANTO EMBALAGEM QUANTO NOME_DO_PRODUTO EM ORDEM DECRESCENTE
SELECT EMBALAGEM, NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM, NOME_DO_PRODUTO DESC;

-- **************** ORDENAÇÃO COM LIMITAÇÃO DE SAÍDA ****************
-- SELECIONA OS 5 SUCOS MAIS CAROS
SELECT TOP 5 NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC;

-- Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limao" em quantidade?
SELECT * FROM ITENS_NOTAS_FISCAIS
SELECT * FROM [dbo].[TABELA_DE_PRODUTOS] -- FAZER INNER JOIN COM CODIGO DO PRODUTO

SELECT TOP 1 NOME_DO_PRODUTO, QUANTIDADE 
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
WHERE nome_do_produto = 'Linha Refrescante - 1 Litro - Morango/Limao'
ORDER BY QUANTIDADE DESC;
--Linha Refrescante - 1 Litro - Morango/Limao QTD 98

-- OU
-- JEITO DO PROF.
-- Primeiro, buscar o código do produto "Linha Refrescante - 1 Litro - Morango/Limão"
SELECT * FROM TABELA_DE_PRODUTOS 
WHERE nome_do_produto = 'Linha Refrescante - 1 Litro - Morango/Limao';

-- Com esta consulta obtemos o resultado do código deste produto: '1101035'. Com esta informação em mãos, 
-- fazemos a consulta para achar a maior quantidade vendida deste produto
SELECT * FROM ITENS_NOTAS_FISCAIS
WHERE codigo_do_produto = '1101035'
ORDER BY QUANTIDADE DESC;

-- RESP 98