-- INSERINDO PRODUTOS PARA DEPOIS EXCLUIR
  INSERT INTO [VENDAS SUCOS 2].[dbo].[PRODUTOS] (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
     VALUES ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50),
	 ('1001000','Sabor dos Alpes 700 ml - Mel�o','Mel�o','700 ml','Garrafa',7.50),
	 ('1001002','Sabor dos Alpes 700 ml - Graviola','Graviola','700 ml','Garrafa',7.50),
	 ('1001003','Sabor dos Alpes 700 ml - Tangerina','Tangerina','700 ml','Garrafa',7.50),
	 ('1001004','Sabor dos Alpes 700 ml - Abacate','Abacate','700 ml','Garrafa',7.50),
	 ('1001005','Sabor dos Alpes 700 ml - A�ai','A�ai','700 ml','Garrafa',7.50),
	 ('1001006','Sabor dos Alpes 1 Litro - Manga','Manga','1 Litro','Garrafa',7.50),
	 ('1001007','Sabor dos Alpes 1 Litro - Mel�o','Mel�o','1 Litro','Garrafa',7.50),
	 ('1001008','Sabor dos Alpes 1 Litro - Graviola','Graviola','1 Litro','Garrafa',7.50),
	 ('1001009','Sabor dos Alpes 1 Litro - Tangerina','Tangerina','1 Litro','Garrafa',7.50),
	 ('1001010','Sabor dos Alpes 1 Litro - Abacate','Abacate','1 Litro','Garrafa',7.50),
	 ('1001011','Sabor dos Alpes 1 Litro - A�ai','A�ai','1 Litro','Garrafa',7.50)

SELECT * FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS] 
WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

-- EXCLUINDO UMA LINHA PELO CODIGO DO PRODUTO
DELETE FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS] WHERE CODIGO = '1001000';
SELECT * FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS] WHERE CODIGO = '1001000';

-- DELETANDO TDS OS PRODUTOS QUE SÃO DESCRITOS COMO SABOR DOS ANDES E TEM TAMANHO DE 1L
SELECT * FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS]
WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'
AND TAMANHO = '1 LITRO'

DELETE FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS]
WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'
AND TAMANHO = '1 LITRO'

-- EXCLUSÃO BASEADA EM PRODUTOS EXISTENTES EM OUTRA TB

SELECT COUNT (*) FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS];
SELECT COUNT (*) FROM [SUCOS_FRUTAS].[dbo].[TABELA_DE_PRODUTOS];

-- PEGANDO PRODUTOS QUE EXISTEM NA TB DE PRODUTOS DO [VENDAS SUCOS 2] MAS NÃO EXITEM NA TB D PRODUTOS NO [SUCOS_FRUTAS]
SELECT * FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS]
WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM [SUCOS_FRUTAS].[dbo].[TABELA_DE_PRODUTOS]);

-- EXCLUIR ESSES PRODUTOS QUE ESTÃO EM UMA TB MAS NÃO NA OUTRA
DELETE FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS]
WHERE CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM [SUCOS_FRUTAS].[dbo].[TABELA_DE_PRODUTOS]);

-- Exclua as notas fiscais (apenas o cabeçalho) cujos clientes tenham entre 18 e 20 anos.
SELECT N.NUMERO FROM [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS] N
INNER JOIN [SUCOS_FRUTAS].[dbo].[TABELA_DE_CLIENTES] C ON N.[CPF] = C.[CPF] 
WHERE C.[IDADE] BETWEEN 18 AND 20

-- ERRO | CONFLITO: NUMERO É FK DA TB [ITENS_NOTAS_FISCAIS] POR ISSO NÃO PODE SER EXCLUIDA
DELETE N FROM [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS] N
INNER JOIN [SUCOS_FRUTAS].[dbo].[TABELA_DE_CLIENTES] C ON N.[CPF] = C.[CPF] 
WHERE C.[IDADE] BETWEEN 18 AND 20

--SELECT * FROM [SUCOS_FRUTAS].[dbo].[NOTAS_FISCAIS]
--SELECT * FROM [SUCOS_FRUTAS].[dbo].[TABELA_DE_CLIENTES] WHERE IDADE BETWEEN 18 AND 20

-- ⚠️😱❌NUNCA FAÇA UM UPDATE OU DELETE SEM WHERE!!!!

-- COPIANDO DADOS DE UMA TB PARA OUTRA PARA TESTAR DELETE E UPDATE SEM WHERE
INSERT INTO [VENDAS SUCOS 2].[dbo].[PRODUTOS_2] SELECT * FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS];
SELECT * FROM [VENDAS SUCOS 2].[dbo].[PRODUTOS_2]

UPDATE PRODUTOS_2 SET SABOR = 'UVA' -- IRÁ ALTERAR TDS OS VALORES COM CAMPO SABOR PARA UVA

DELETE FROM PRODUTOS_2; -- APAGA TDS OS DADOS DA TB

