/*
Durante os exercícios anteriores, realizamos algumas consultas e entre elas estava 
a consulta abaixo que foi resposta de um exercício anterior.

Uma vez que essa consulta foi realizada nestes moldes, refaça esta consulta usando Subconsultas.
*/

-- produtos cuja soma das vendas são maiores que 1000
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 1000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

-- COM SUBCONSULTA
SELECT SC.CODIGO_DO_PRODUTO, 
	   SC.NOME_DO_PRODUTO, 
	   SC.QUANTIDADE_TOTAL
FROM
	(SELECT INF.CODIGO_DO_PRODUTO, 
			TP.NOME_DO_PRODUTO, 
	SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL FROM ITENS_NOTAS_FISCAIS  INF -- ALIAS DE SUM QUANTIDADE É QUANTIDADE_TOTAL
	
	INNER JOIN TABELA_DE_PRODUTOS TP 
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
	GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) SC -- SC ALIAS DA CONSULTA DENTRO DO FROM

WHERE SC.QUANTIDADE_TOTAL > 1000 
ORDER BY SC.QUANTIDADE_TOTAL DESC;
