-- Quais clientes estão localizados em bairros onde tem mais vendedores?
SELECT COUNT(*) FROM TABELA_DE_CLIENTES; --16 clientes

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES; -- 4 vendedores

-- APENAS 7 CLIENTES TEM VENDEDORES EM SEUS BAIRROS
SELECT 
	  TV.NOME AS NOME_DO_VENDEDOR
	, TV.BAIRRO AS BAIRRO_DO_VENDEDOR
	, TC.BAIRRO AS BAIRRO_DO_CLIENTE
	, TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC 
INNER JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO

-- QUAL VENDEDOR NÃO TEM CLIENTE EM SEU BAIRRO?
SELECT 
	  TV.NOME AS NOME_DO_VENDEDOR
	, TV.BAIRRO AS BAIRRO_DO_VENDEDOR
	, TC.BAIRRO AS BAIRRO_DO_CLIENTE
	, TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC 
RIGHT JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.NOME IS NULL
-- TRAZ OS VENDEDORES QUE TIVEREM OS CAMPOS BAIRRO_DO_CLIENTE E NOME_DO_CLIENTE NULOS

-- QUAIS CLIENTES QUE MORAM EM BAIRROS QUE NÃO TEM VENDEDORES?
SELECT 
	  TV.NOME AS NOME_DO_VENDEDOR
	, TV.BAIRRO AS BAIRRO_DO_VENDEDOR
	, TC.BAIRRO AS BAIRRO_DO_CLIENTE
	, TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC 
LEFT JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL

-- A RESPOSTA AS DUAS PERGUNTAS PODE SER FEITA COM UM FULL JOIN
SELECT 
	  TV.NOME AS NOME_DO_VENDEDOR
	, TV.BAIRRO AS BAIRRO_DO_VENDEDOR
	, TC.BAIRRO AS BAIRRO_DO_CLIENTE
	, TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC 
FULL JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
ORDER BY TV.NOME, TC.NOME
