-- 11 Subconsultas no comando IN

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES; -- RESULTADO: Copacabana,Jardins, Santo Amaro, Tijuca   

SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN ('COPACABANA', 'JARDINS', 'SANTO AMARO', 'TIJUCA');

-- SUB QUERY | PARA USAR UMA SUB QUERY DENTRO DO IN O RESULTADO DA SUB QUERY TEM Q TER SÓ UM CAMPO (NO CASO AQUI "BAIRRO")
SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);


/*
Veja a consulta abaixo que foi resposta de um exercício anterior.
Ela nos dá os produtos cuja soma das vendas são maiores que 394000 (substituir por 1000).

Levando isso em consideração, liste os sabores destes produtos que são selecionados nesta consulta.

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

*/
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT 
	INF.CODIGO_DO_PRODUTO, 
	TP.NOME_DO_PRODUTO, 
	TP.SABOR, 
	SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO

WHERE SABOR IN (SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS)

GROUP BY INF.CODIGO_DO_PRODUTO, 
		 TP.NOME_DO_PRODUTO, 
		 TP.SABOR 
		 HAVING SUM(INF.QUANTIDADE) > 1000 
ORDER BY SUM(INF.QUANTIDADE) DESC

-- OU TRAZENDO APENAS OS CAMPO SABOR

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS WHERE
CODIGO_DO_PRODUTO IN (
					  SELECT INF.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS  INF
					  INNER JOIN TABELA_DE_PRODUTOS TP 
					  ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 1000 );