-- 13 Subconsultas substituindo o HAVING

-- MÉDIA DE PREÇOS DOS TIPOS DE EMBALAGEM DE SUCO
SELECT EMBALAGEM, AVG (PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

-- PEGA AS EMBALAGENS COM PREÇO MÉDIO < OU = A 10 USANDO HAVING
SELECT EMBALAGEM, AVG (PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
HAVING AVG (PRECO_DE_LISTA) <= 10;

-- COM SUB QUERY
SELECT MEDIA_EMBALAGENS.EMBALAGEM,
	   MEDIA_EMBALAGENS.PRECO_MEDIO
FROM
	(SELECT EMBALAGEM, AVG (PRECO_DE_LISTA) AS PRECO_MEDIO
	FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM) MEDIA_EMBALAGENS -- ALIAS DA CONSULTA
WHERE MEDIA_EMBALAGENS.PRECO_MEDIO <= 10;