-- UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES; -- 12 bairros

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES; -- 4 bairros

-- UNION AUTOMATICAMENTE APLICA UM DISTINC AO RESULTADO FINAL (NÃO DUPLICA DADOS)
SELECT BAIRRO FROM TABELA_DE_CLIENTES 
UNION 
SELECT BAIRRO FROM TABELA_DE_VENDEDORES
ORDER BY BAIRRO;

-- UNION ALL NÃO APLICA O DISCTINC
SELECT BAIRRO FROM TABELA_DE_CLIENTES 
UNION ALL 
SELECT BAIRRO FROM TABELA_DE_VENDEDORES;

-- UNION ALL JUNTA TODOS OS VALORES INDEPENDENTMENTE DE SEREM DUPLICADOS MESMO COLOCANDO O DISTINCT
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES 
UNION ALL 
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES
order by BAIRRO;

-- MOSTRANDO TBM A ORIGEM DO DADO (DE QUAL TABELA VEM O DADO) 
-- MAS NÃO CONSEGUE APLICAR O DISTINC POR CAUSA DA DIFERENÇA Q TRAZ A NOVA COL DE ORIGEM
SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES -- O ALIAS MEIO CRIA UMA COLUNA NA CONSULTA PARA APONTAR A ORIGEM DO DADO
UNION ALL 
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES
ORDER BY BAIRRO;

-- MESMA CONSULTA MAS SEM O ALL, MESMO RESULTADO
SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES 
UNION 
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES
ORDER BY BAIRRO;

