-- FUNÇÕES DE TEXTO (NATIVA DO SQL SERVER) 

SELECT LOWER('o jOÃO eSTEVE lá em casa') -- CONVERTE O Q ESTIVER EM MAIÚSCULA PARA MINÚSCULA 

SELECT UPPER('o jOÃO eSTEVE lá em casa') -- CONVERTE O Q ESTIVER EM MINÚSCULA PARA MAIÚSCULA

SELECT CONCAT('O JOÃO', ' ESTEVE ', 'LÁ EM CASA') -- CONCATENA AS STRINGS

SELECT RIGHT('O JOÃO ESTEVE LÁ EM CASA', 6) -- RETORNA A PARTE DIREITA DE UMA CADEIA DE CARACTERES, USANDO COMO PARÂMETRO O NUMERO PASSADO, NO CASO 6

SELECT LEFT('O JOÃO ESTEVE LÁ EM CASA', 6) -- FAZ O INVERSO DA FUNC RIGHT

SELECT REPLICATE('O JOÃO ESTEVE LÁ EM CASA ', 2) --REPETE OVALOR DE CARACTERES QUE ESTÁ NA FUNÇÃO, USANDO COMO PARÂMETRO O NUMERO PASSADO, NO CASO 2

-- RETORNA UMA PARTE DA STRING A PARTIR DO PONTO (PASSADO NO SEGUNDO PRÂMETRO NO CASO 3)  
-- E A QUANTIDADE DE CARACTERES A SEREM EXTRAÍDOS (PASSADO NO TERCEIRO PARÂMETRO NO CASO 10) 
SELECT SUBSTRING('O JOÃO ESTEVE LÁ EM CASA', 3, 10) -- SAÍDA "JOÃO ESTEV"

SELECT LTRIM('          O JOÃO ESTEVE LÁ EM CASA') -- TIRA OS ESPAÇOS À ESQUERDA DA FRASE

SELECT RTRIM('O JOÃO ESTEVE LÁ EM CASA          ')-- TIRA OS ESPAÇOS À DIREITA DA FRASE

SELECT TRIM('      O JOÃO ESTEVE LÁ EM CASA      ')-- TIRA OS ESPAÇOS DOS DOIS LADOS

-- SUBSTITUI UM CONJUNTO DE CARACTERES POR OUTRO ESPECIFICADO, NO CASO -
SELECT REPLACE('O JOÃO ESTEVE LÁ EM CASA', ' ', '-') -- SAÍDA "O-JOÃO-ESTEVE-LÁ-EM-CASA"

-- CONTA O NUMERO DE CARACTERES INCLUINDO ESPAÇOS NO MEIO DA STRING, MAS ABSTRAINDO ESPAÇOS À DIREITA (NO FIM) DA STRING
SELECT LEN('O JOÃO ESTEVE LÁ EM CASA ')-- SAÍDA 24
SELECT LEN('O JOÃO  ESTEVE LÁ EM CASA ')-- SAÍDA 25

SELECT * FROM TABELA_DE_CLIENTES

-- MOSTRA O CAMPO NOME DO CLIENTE ANTES E DEPOIS DE APLICAR A FUNC
SELECT NOME, LOWER (NOME) AS NOME_MINUSCULO FROM TABELA_DE_CLIENTES;

SELECT NOME, UPPER (NOME) AS NOME_MAIUSCULO FROM TABELA_DE_CLIENTES;

-- CONCATENA TDS OS CAMPOS DO ENDEREÇO DO CLIENTE EM ENDERECO_COMPLETO
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, ' ', CEP) AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

-- OUTRO JEITO SEM A FUN C CONCAT
SELECT NOME, ENDERECO_1 + ' '+ BAIRRO + ' '+ CIDADE + ' ' + ESTADO + ' ' + CEP AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS

-- PEGA OS 3 PRIMEIROS CARACTERES DO NOME DO PRODUTO
SELECT NOME_DO_PRODUTO, LEFT (NOME_DO_PRODUTO, 3) AS TRES_PRIMEIROS_CARACTERES FROM TABELA_DE_PRODUTOS

-- SUBSTITUIDO (NA CONSULTA) LITRO E LITROS POR L
SELECT TAMANHO, REPLACE ((REPLACE(TAMANHO, 'Litros', 'L')), 'Litro', 'L') AS TAMANHO_MODIFICADO FROM TABELA_DE_PRODUTOS

/*
Conforme vimos nas aulas sobre funções de texto, observe a seguinte frase abaixo:

CIDADE DO RIO DE JANEIRO

Como seria a função para retirar deste texto somente a palavra RIO?
*/
SELECT SUBSTRING('CIDADE DO RIO DE JANEIRO', 11, 3)

/*
Nas aulas relacionadas às funções de texto, observamos a tabela de cliente onde podemos listar os nomes.

Note que os nomes e sobrenomes são separados por um espaço.

Sendo assim, faça uma consulta que traga somente o primeiro nome de cada cliente.

Dica: Como foi dito pelo instrutor existem diversas funções do SQL Server e muitas vezes não sabemos todas. 
Por isso, para resolver este problema pesquise sobre a função CHARINDEX, veja como ela funciona, 
e aplique para resolver este problema.

Essa função pesquisa uma expressão de caractere dentro de uma segunda expressão de caractere, 
retornando a posição inicial da primeira expressão, se localizada.
SINTAXE: CHARINDEX ( expressionToFind , expressionToSearch [ , start_location ] )
*/
SELECT NOME FROM TABELA_DE_CLIENTES ORDER BY NOME;

-- ENCONTRA O NUM DE CARACTERES DO PRIMEIRO NOME DE CADA CLIENTE INCLUINDO O ESPAÇO
-- PARA ENCONTRAR O ESPAÇO NA STRING
SELECT NOME, CHARINDEX(' ', NOME, 1) AS QTD_CARACTERES_PRIMEIRO_NOME FROM TABELA_DE_CLIENTES

-- PARA PEGAR O PRIMEIRO NOME USAR O CHARINDEX DENTRO DE SUBSTRING
-- (PEGA 1° NOME EXCUINDO TBM O ESPAÇO APÓS ELE)
SELECT
	SUBSTRING(NOME, 1, CHARINDEX(' ', NOME) -1) AS PRIMEIRO_NOME
FROM TABELA_DE_CLIENTES
ORDER BY NOME;

-- OU
-- TARZENDO TBM A COL COM O NOME COMPLETO (PEGA 1° NOME COM O ESPAÇO APÓS ELE)
SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) 
FROM TABELA_DE_CLIENTES 
ORDER BY NOME;

-- OBS.: UM CLIENTE SEM ESPAÇO ENTRE OS NOMES RETORNARÁ COM O VALOR VAZIO

-- E CASO NÃO HAJA ESPAÇO ENTRE NOME E SOBRENOME?

--INSERINDO UM CLIENTE SEM ESPAÇO ENTRE OS NOMES
INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2,BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO,
LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES ('73012632335', 'NatashaRomanoff', 'Rua das Laranjeiras', ' ', 'Laranjeiras', 'Rio de
Janeiro', 'RJ', '23401020', '1987-01-01', 38, 'F', '200000', '34000', 0);


-- GARANTE QUE, CASO NÃO HOUVER ESPAÇO NA STRING (ENTRE NOME E SOBRENOME), A PRÓPRIA STRING SERÁ 
-- RETORNADA COMO "PRIMEIRO NOME" AO INVÉS DE RETORNAR UM CAMPO VAZIO.
SELECT
    NOME,
    CASE 
        WHEN CHARINDEX(' ', NOME) > 0 THEN SUBSTRING(NOME, 1, CHARINDEX(' ', NOME) - 1)
        ELSE NOME
    END AS PRIMEIRO_NOME
FROM TABELA_DE_CLIENTES
WHERE CPF = '73012632335'
ORDER BY NOME;
