-- 05 Funções de datas

SELECT DATEADD(DAY, 30, '2024-01-01') -- CONTA 30 DIAS A FRENTE

SELECT DATEADD(DAY, -30, '2024-01-01') -- CONTA 30 DIAS P TRÁS

SELECT DATEDIFF(DAY, '2025-01-20', '2025-01-31') -- CONTA DIFERENÇA ENTRE DOIS DIAS

SELECT DATEDIFF(MONTH, '2025-01-20', '2025-10-31') -- CONTA DIFERENÇA ENTRE MESES

-- fun datepart, passa uma data e a saída pode ser o ano, o mês, o dia, a hora, o minuto dessa data.
SELECT DATEPART(DAY, '2025-01-19') -- retorno é o dia 19

SELECT GETDATE() -- PEGA A DATA E HORA ATUAL

-- SOMA 10 DIAS AO DIA DE HJ
SELECT DATEADD(DAY, 10, GETDATE());
SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS;


-- PEGAR A DATA DE 48 DIAS ATRÁS
SELECT DATEADD(DAY,-48, GETDATE()) AS DATA_48_DIAS_ATRAS



SELECT DAY('19-01-2025') AS DIA--PEGA SÓ O DIA DA DATA

SELECT MONTH('19-01-2025') AS MÊS --PEGA SÓ O MÊS DA DATA

SELECT YEAR('19-01-2025') AS ANO--PEGA SÓ O ANO DA DATA

SELECT ISDATE('30-02-2025') -- RETORNA 1 SE A DATA FOR VÁLIDA E 0 SE NÃO FOR
SELECT ISDATE('19-01-2025')

--SELECT 
--    CASE 
--        WHEN TRY_CAST(DATETIME2FROMPARTS(2025, 02, 28, 0, 0, 0, 0, 0) AS DATETIME2) IS NOT NULL THEN 1
--        ELSE 0
--    END AS É_UMA_DATA_VÁLIDA;


-- vai retornar uma data baseado em inteiros separados por vírgula
-- sintaxe DATETIMEFROMPARTS(ano, mes, dia, hora, minuto, segundos, milissegundo)
SELECT DATETIMEFROMPARTS(2025, 01, 19, 15, 18, 20, 30)

-- QUANTOS DIAS DE PASSARAM DESDE A DATA PASSADA NO PARÂMETRO
SELECT DATEDIFF(DAY, '2024-12-17', GETDATE()) AS QTD_DIAS_DEPOIS;

-- NUM DE HORAS DESDE O RPIRMEIRO DIA DO ANO
SELECT DATEDIFF(HOUR, '2025-01-01', GETDATE()) AS HORAS_DESDE_INICIO_ANO;

-- NUM DE MESES DESDE O INCIO DO ANO
SELECT DATEDIFF(MONTH, '2025-01-01', GETDATE()) AS MESES_DESDE_INICIO_ANO;

-- PEGA O DIA DE HJ (MOMENTO DE EXCEUÇÃO DA FUNC)
SELECT DATEPART(DAY, GETDATE()) AS DIA_DE_HOJE;

SELECT * FROM TABELA_DE_CLIENTES

/*
Sobre o tema relativo a funções de datas, vamos considerar a seguinte situação problema: 
como eu poderia calcular o número de anos que uma pessoa viveu desde o seu nascimento?
*/
SELECT NOME, DATEDIFF(YEAR, DATA_DE_NASCIMENTO, GETDATE()) AS IDADE FROM TABELA_DE_CLIENTES;

/*
Como seria a consulta que retornasse o nome do cliente e sua data de nascimento 
por extenso dia, dia da semana, mês e ano?

Dica: Mais uma função de data que você deve pesquisar na documentação. 
Chama-se DATENAME. Use ela concatenando com o nome do cliente.

SINTAXE: DATENAME ( datepart , date )
*/

SELECT 
    NOME,
    CONCAT(
        DATENAME(DW, DATA_DE_NASCIMENTO), ', ', -- DW RETORNA O NOME DO DIA DA SEMANA
        DATENAME(DAY, DATA_DE_NASCIMENTO), ' de ',
        DATENAME(MONTH, DATA_DE_NASCIMENTO), ' de ',
        DATENAME(YEAR, DATA_DE_NASCIMENTO)
    ) AS DATA_DE_NASCIMENTO
FROM 
    TABELA_DE_CLIENTES
	ORDER BY NOME

-- RESP PROF (DIFERENÇA: RETONA TUDO EM UMA ÚNICA COL)
SELECT NOME + ' nasceu em ' + 
	DATENAME (WEEKDAY,DATA_DE_NASCIMENTO) + ',' +
	DATENAME (DAY,DATA_DE_NASCIMENTO) + ' de ' +
	DATENAME(MONTH, DATA_DE_NASCIMENTO) + ' de ' +
	DATENAME(YEAR, DATA_DE_NASCIMENTO) AS DATA_EXTENSO
FROM TABELA_DE_CLIENTES;



-- RETORNA O DIA DA SEMANA DE UMA DETERMINADA DATA
SELECT  DATENAME(DW, '1950-01-01')