SELECT CPF, NOME, [DATA DE NASCIMENTO], IDADE
FROM [dbo].[TABELA DE CLIENTES]

SELECT DATEDIFF(YEAR, '1992-01-05', GETDATE()) -- OUTPUT é a idade de quem nasceu nessa data

-- mostra a difrença entre as idades registradas defasadas
SELECT CPF, NOME, [DATA DE NASCIMENTO], IDADE, DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
FROM [dbo].[TABELA DE CLIENTES]

-- PROCEDURE QUE VAI ATUALIZAR A IDADE DA TABELA DE CLIENTES

CREATE PROCEDURE AtualizaIdade
AS BEGIN
	UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END;

INSERT INTO [TABELA DE CLIENTES]
(CPF, NOME, [ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO],IDADE, SEXO,[LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA])
VALUES
('12312312312', 'Ana Maria', 'Rua Das Flores', 'Paraíso', 'São Paulo', 'SP', '20000', '2000-01-01', 10, 'F', 1000, 12000, 1);

-- executando a proc

EXEC [dbo].[AtualizaIdade] -- APÓS A EXECUÇÃO ATUALIZA A IDADE DE TDS OS CLIENTES DA BASE


