SELECT COUNT (*) FROM TABELA_DE_CLIENTES;
SELECT COUNT (*) FROM TABELA_DE_PRODUTOS;
SELECT COUNT (*) FROM TABELA_DE_VENDEDORES;
SELECT COUNT (*) FROM NOTAS_FISCAIS;
SELECT COUNT (*) FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM TABELA_DE_CLIENTES;

--SELECT COM CAMPOS ESPECIFICOS
SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, CIDADe, BAIRRO FROM TABELA_DE_CLIENTES;

--ALIAS ÚTIL PARA DIFERENCIAR CAMPOS COM MESMO NOME EM TABELAS DIFERENTES
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTE], BAIRRO, CIDADE 
FROM TABELA_DE_CLIENTES TDC; -- A TABELA TBM PODE TER UM ALIAS MAS NÃO PRECISA COLOCAR O "AS"

SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;

--SELECT COM FILTRO SIMPLES
SELECT * FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '243083';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE EMBALAGEM = 'pet';

