-- Controle de fluxo usando VARIÁVEIS e controle se fluxo usando o SELECT

--DECLARE @CPF VARCHAR(15);
--DECLARE @IDADE_TABELA INT;
--DECLARE @DATA_NASCIMENTO DATE;
--DECLARE @IDADE INT;

SET @CPF = '5648641702';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE_TABELA = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
--IF @IDADE_TABELA <> @IDADE UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF;

SELECT COUNT(*) FROM  [TABELA DE CLIENTES] -- o valor de COUNT(*) será 1 se a IDADE da tabela for diferente de @IDADE
WHERE CPF = @CPF AND IDADE <> @IDADE -- Para testar execute o script com a linha de update comentada

PRINT CONCAT('Idade desatualizada: ' , @IDADE_TABELA) -- mostra a idade desatualizada
PRINT CONCAT('Idade atualizada: ' , @IDADE); -- mostra a idade atualizada

SELECT CPF, NOME, [DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES] WHERE CPF = '5648641702';

SELECT * FROM [TABELA DE CLIENTES]
----------------------------------------------------------------------
--como podemos reescrever este SCRIPT usando um SELECT no teste do IF?

DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE_ATUALIZADA INT;
DECLARE @IDADE_DESATUALIZADA INT;

SET @CPF = '5576228758';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE_ATUALIZADA = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());

SELECT @IDADE_DESATUALIZADA = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF; --ATRIBUINDO VALOR A IDADE DA TABELA SÓ PARA PRINTAR ANTES DA ALTERAÇÃO

IF (SELECT COUNT(*) FROM  [TABELA DE CLIENTES] WHERE CPF = @CPF AND IDADE <> @IDADE_ATUALIZADA) = 1 
    UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE_ATUALIZADA WHERE CPF = @CPF;

PRINT CONCAT('Idade desatualizada: ' , @IDADE_DESATUALIZADA) -- mostra a idade desatualizada
PRINT CONCAT('Idade atualizada: ' , @IDADE_ATUALIZADA); -- mostra a idade atualizada

SELECT CPF, NOME, [DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES] WHERE CPF = '5576228758';
