-- Base SUCOS_FRUTAS
-- **************** Expressões lógicas ****************

-- SUCO DE MANGA DE 470ML
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA' AND TAMANHO = '470 ML'

-- TRAS OS SUCOS Q ATENDEM A ESSES FILTROS: SABOR MANGA E 470ML
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA' OR TAMANHO = '470 ML'

-- TRAZ OS SUCOS QUE NÃO ESTÃO NAS CONDIÇÕES DO FILTRO
SELECT SABOR, TAMANHO FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'MANGA' AND TAMANHO = '470 ML');

-- TRAZ OS SUCOS QUE OU NÃO SÃO DE MANGA OU NÃO TAM 470 ML
SELECT SABOR, TAMANHO FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'MANGA' OR TAMANHO = '470 ML')
ORDER BY SABOR, TAMANHO;

-- TRAZ OS SUCOS Q É OU DE LARANJA OU DE MANGA OU DE MELACIA
SELECT SABOR FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA' 
	OR SABOR = 'MELACIA'
	OR SABOR = 'LARANJA';

-- OUTRA FORMA DE CONSULTAR | IN SUBSTITUI VÁRIOS OR ENCADEADOS
SELECT SABOR FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('MANGA', 'MELACIA', 'LARANJA');

-- USANDO MAIS UMA CONDIÇÃO JUNTA
SELECT SABOR, TAMANHO FROM TABELA_DE_PRODUTOS
WHERE (SABOR IN ('MANGA', 'MELACIA', 'LARANJA') AND TAMANHO = '1 LITRO');

-- CLIENTES DO RIO E SP
SELECT NOME, CIDADE FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')

-- CLIENTES DO RIO E SP DE 20A PRA CIMA
SELECT NOME, IDADE, CIDADE FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')
AND IDADE >= 20;

-- CLIENTES DO RIO E SP ENTRE 20 E 25 ANOS
SELECT NOME, CIDADE, IDADE FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')
AND (IDADE >= 20 AND IDADE <= 25)
ORDER BY IDADE;

-- MESMA CONSULTA, USANDO BETWEEN
SELECT NOME, CIDADE, IDADE FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('RIO DE JANEIRO', 'SAO PAULO')
AND (IDADE BETWEEN 20 AND 25)
ORDER BY IDADE;

