-- 07 Agrupando linhas das tabelas

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES;

-- ODENANDO POR IDADE
SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES
ORDER BY CIDADE, IDADE;

-- AGRUPANDO OS CLIENTES POR CIDADE E SOMANDO A IDADE DELES EM CADA CIDADE
SELECT CIDADE, SUM(IDADE) AS IDADE FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- USANDO MAIS DE UM INDICADOR AO MESMO TEMPO | SOMA DAS IDADES E DOS LIM DE CREDITO
SELECT CIDADE, SUM(IDADE) AS IDADE, 
			   SUM(LIMITE_DE_CREDITO) AS CRÉDITO  
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- MEDIA DE IDADE
SELECT CIDADE, AVG(IDADE) AS MEDIA_IDADE, 
			   SUM(LIMITE_DE_CREDITO) AS CRÉDITO  
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- CONTA NUM DE CLIENTES EM CADA CIDADE
SELECT CIDADE, COUNT (*) AS NUMERO_DE_CLIENTES 
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- CONTA NUM DE PRODUTOS POR EMBALAGEM APENAS DOS SUCOS DE LARANJA
SELECT EMBALAGEM, COUNT (*) AS NUMERO_DE_CLIENTES
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'LARANJA'
GROUP BY EMBALAGEM;

/*
Cada item da nota fiscal representa 1 venda de um determinado produto.
Vimos no exercício anterior que temos várias vendas com quantidade igual a 98 litros para o produto '1101035'.
Pergunto: Quantas vendas foram feitas com quantidade igual a 98 litros para o produto '1101035'?
*/
select * FROM [dbo].[ITENS_NOTAS_FISCAIS] ORDER BY QUANTIDADE DESC

SELECT CODIGO_DO_PRODUTO, QUANTIDADE, COUNT(*) AS NUMERO_DE_VENDAS
FROM ITENS_NOTAS_FISCAIS
WHERE QUANTIDADE = 98 AND CODIGO_DO_PRODUTO = '1101035'
GROUP BY QUANTIDADE, CODIGO_DO_PRODUTO;
-- RESP 1

-- PEGANDO DE OUTRO PRODUTO
SELECT CODIGO_DO_PRODUTO, COUNT(*) AS  NUMERO_DE_VENDAS 
FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = '788975' AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO;
-- RESP 3