SELECT COUNT (*) FROM TABELA_DE_CLIENTES;
SELECT COUNT (*) FROM TABELA_DE_PRODUTOS;
SELECT COUNT (*) FROM TABELA_DE_VENDEDORES;
SELECT COUNT (*) FROM NOTAS_FISCAIS;
SELECT COUNT (*) FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM TABELA_DE_CLIENTES;

--SELECT COM CAMPOS ESPECIFICOS
SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, CIDADe, BAIRRO FROM TABELA_DE_CLIENTES;

--ALIAS ÚTIL PARA DIFERENCIAR CAMPOS COM MESMO NOME EM TABELAS DIFERENTES
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTE], BAIRRO, CIDADE 
FROM TABELA_DE_CLIENTES TDC; -- A TABELA TBM PODE TER UM ALIAS MAS NÃO PRECISA COLOCAR O "AS"

SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;

--SELECT COM FILTRO SIMPLES
SELECT * FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '243083';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE EMBALAGEM = 'pet';

--filtros quantitativos
SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE > 20

SELECT * FROM TABELA_DE_CLIENTES
WHERE IDADE < 20

SELECT * FROM TABELA_DE_CLIENTES --CLIENTES COM 18 ANOS OU MAIS
WHERE IDADE <= 18;

SELECT * FROM TABELA_DE_CLIENTES --CLIENTES MENORES DE 18 ANOS
WHERE IDADE < 18;

SELECT * FROM TABELA_DE_CLIENTES --CLIENTES COM IDADE DIFERENTE DE 18 ANOS
WHERE IDADE <> 18;

--FILTRO COM DATA
SELECT * FROM TABELA_DE_CLIENTES
WHERE DATA_DE_NASCIMENTO >= '1995-11-14'; --CLIENTES Q NASCERAM A PARTIR DESSA DATA

SELECT * FROM TABELA_DE_CLIENTES
WHERE DATA_DE_NASCIMENTO < '1995-11-14'; --CLIENTES Q NASCERAM A ANTES DESSA DATA

--CONSULTA POR ORGEM ALFABÉTICA
SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO >= 'LAPA'; --TRAZ OS CLIENTES Q MORAM EM BAIRROS CUJA LETRA INICIA A PARTIR DA LETRA L