-- func que concatena o endereço do cliente
select * from [TABELA DE CLIENTES]

CREATE FUNCTION EnderecoCompleto
( -- PARÂMETROS
@ENDERCO VARCHAR (100),
@BAIRRO VARCHAR (50),
@CIDADE VARCHAR (100),
@ESTADO VARCHAR (20),
@CEP VARCHAR (20)
)
RETURNS VARCHAR (250)
AS

BEGIN
	DECLARE @ENDERECO_COMPLETO VARCHAR(250)
	SET @ENDERECO_COMPLETO = @ENDERCO + ' - ' + @BAIRRO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP
	RETURN @ENDERECO_COMPLETO
END

-- CHAMADA DA FUNC
SELECT CPF,[dbo].[EnderecoCompleto] ([ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP) AS [Endereço completo]
from [TABELA DE CLIENTES]

-- ALTERANDO A FUNC EnderecoCompleto
ALTER FUNCTION EnderecoCompleto
( -- PARÂMETROS
@ENDERCO VARCHAR (100),
@BAIRRO VARCHAR (50),
@CIDADE VARCHAR (100),
@ESTADO VARCHAR (20),
@CEP VARCHAR (20)
)
RETURNS VARCHAR (250)
AS

BEGIN
	DECLARE @ENDERECO_COMPLETO VARCHAR(250)
	SET @ENDERECO_COMPLETO = @ENDERCO + '  ' + @BAIRRO + '  ' + @CIDADE + '  ' + @ESTADO + ' , CEP ' + @CEP
	RETURN @ENDERECO_COMPLETO
END

