SELECT RAND()

-- NUM ALEATÓRIOS ENTRE 100 E 500
SELECT ROUND(((500 -100 - 1) * RAND() +100), 0)

-- atribui RAND a uma VISÃO pq RAND não pode ser usada dentro da função criada
CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALOR_ALEATORIO

SELECT * FROM VW_ALEATORIO

-- Func num aleatorio passa o valor min e o max e retorna um num aleatório
CREATE FUNCTION NumeroAleatorio(@VALOR_MIN INT, @VALOR_MAX INT)
RETURNS INT
AS
BEGIN
	DECLARE @NUM_ALEATORIO INT
	DECLARE @VALOR_ALEATORIO FLOAT
	SELECT @VALOR_ALEATORIO = VALOR_ALEATORIO FROM VW_ALEATORIO --VARIÁVEL VALOR_ALEATORIO RECEBE O CAMPO VALOR_ALEATORIO QUE VEM DA VISÃO
	SET @NUM_ALEATORIO = ROUND(((@VALOR_MAX - @VALOR_MIN -1) * @VALOR_ALEATORIO + @VALOR_MIN), 0)
	RETURN @NUM_ALEATORIO
END

SELECT dbo.[NumeroAleatorio](1,10) -- gera numeros aleatórios entre os parâmetros passados
